language: php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source --no-interaction

script: ./vendor/phpunit/phpunit/composer/bin/phpunit
